/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "secondary-container": "#7af7e8",
        "inverse-on-surface": "#f2eff8",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "background": "#fcf8ff",
        "surface-variant": "#e4e1ea",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary": "#006a62",
        "on-surface-variant": "#464652",
        "safety-orange": "#FF6B00",
        "on-tertiary-container": "#f19160",
        "tertiary-fixed": "#ffdbcb",
        "tertiary": "#491a00",
        "outline-variant": "#c7c5d4",
        "on-surface": "#1b1b21",
        "primary-container": "#2e3192",
        "on-primary-fixed": "#04006d",
        "outline": "#777683",
        "on-tertiary-fixed": "#341100",
        "surface-container-high": "#eae7f0",
        "primary": "#15157d",
        "surface": "#fcf8ff",
        "on-error": "#ffffff",
        "tech-blue": "#007AFF",
        "tertiary-container": "#6c2a00",
        "on-primary-fixed-variant": "#373a9b",
        "secondary-fixed-dim": "#5bdacc",
        "on-secondary-container": "#007168",
        "on-background": "#1b1b21",
        "secondary-fixed": "#7af7e8",
        "surface-tint": "#4f54b4",
        "tertiary-fixed-dim": "#ffb692",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fcf8ff",
        "surface-muted": "#F1F1F1",
        "surface-container-highest": "#e4e1ea",
        "inverse-primary": "#c0c1ff",
        "surface-container": "#f0ecf5",
        "inverse-surface": "#303036",
        "surface-dim": "#dbd9e1",
        "on-secondary-fixed": "#00201d",
        "on-primary-container": "#9da1ff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary-fixed-variant": "#773207",
        "primary-fixed": "#e1e0ff",
        "surface-container-low": "#f5f2fb",
        "slate-gray": "#4A5568",
        "on-secondary-fixed-variant": "#005049"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1280px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "margin-desktop": "40px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
